#Persisted Channels storage file  by EFI Analytics, Inc
#Last Saved on: Fri May 15 22:38:20 EDT 2026
#Fri May 15 22:38:20 EDT 2026
_(\ tsInputSpeedMPH\ /\ 3600.0\ *\ deltatime\ )=0.0
_(\ (\ tsInputSpeedMPH\ *\ 1.60934\ )\ /\ 3600.0\ *\ deltatime\ )=0.0
_(\ (\ deltatime\ <\ 1000.0\ )\ )\ ?\ ((\ (\ tsFuelFlowGph\ *\ deltatime\ /\ 3600.0\ )\ ))\ \:\ (0.0)=0.008794955600657675
